# Generated by Codex on 2026-03-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_payments", "0002_alter_cartitem_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("gross_sales", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("commission_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("payout_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("suborder_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("GENERATED", "Generated"), ("PAID", "Paid")], default="GENERATED", max_length=20)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("generated_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="generated_settlements", to=settings.AUTH_USER_MODEL)),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="settlements", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-week_start", "producer__username"],
            },
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.UniqueConstraint(fields=("producer", "week_start"), name="unique_settlement_per_producer_week"),
        ),
    ]
