# Generated by Codex on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_payments", "0003_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="commission_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="producer_payout_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
