# Generated by Codex on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_orders", "0002_order_customer_phone_order_delivery_address_and_more"),
        ("market_payments", "0004_payment_finance_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="included_suborders",
            field=models.ManyToManyField(blank=True, related_name="settlements", to="market_orders.producersuborder"),
        ),
    ]
