# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_payments", "0005_settlement_included_suborders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settlement",
            name="status",
            field=models.CharField(
                choices=[
                    ("GENERATED", "Generated"),
                    ("FAILED", "Payout failed"),
                    ("PAID", "Paid"),
                ],
                default="GENERATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="payout_provider",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="settlement",
            name="payout_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="settlement",
            name="payout_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="settlement",
            name="payout_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
