# Generated by Django 5.2.11 on 2026-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('NEW_ORDER', 'New Order')], max_length=20),
        ),
    ]
