# Generated by Codex on 2026-03-23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("frequency", models.CharField(choices=[("WEEKLY", "Weekly")], default="WEEKLY", max_length=20)),
                ("template_order_data", models.JSONField(default=dict)),
                ("next_instance_overrides", models.JSONField(blank=True, default=dict)),
                ("next_run_date", models.DateField()),
                ("active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="recurring_orders", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["next_run_date", "id"],
            },
        ),
    ]
