# Generated by Codex on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market_finance", "0001_initial"),
        ("market_payments", "0003_settlement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[],
            options={
                "verbose_name": "Settlement",
                "verbose_name_plural": "Settlements",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("market_payments.settlement",),
        ),
    ]
