# Generated by Codex on 2026-04-19

from django.db import migrations, models


def sync_recurring_status(apps, schema_editor):
    RecurringOrder = apps.get_model("market_finance", "RecurringOrder")
    RecurringOrder.objects.filter(active=True).update(status="ACTIVE")
    RecurringOrder.objects.filter(active=False).update(status="PAUSED")


class Migration(migrations.Migration):

    dependencies = [
        ("market_finance", "0002_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringorder",
            name="preferred_delivery_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recurringorder",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("PAUSED", "Paused"), ("CANCELLED", "Cancelled")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.RunPython(sync_recurring_status, migrations.RunPython.noop),
    ]
