# Generated by Django 5.2.11 on 2026-03-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruit_veg', 'Fruit & Vegetables'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('meat', 'Meat'), ('drinks', 'Drinks'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
