# Generated by Django 5.2.11 on 2026-03-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_products', '0002_product_allergens_product_category_and_more'),
        ('market_products', '0002_review'),
    ]

    operations = [
    ]
