# Generated by Codex on 2026-04-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_products", "0003_merge_20260323_2333"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="moderation_status",
            field=models.CharField(
                choices=[("PUBLISHED", "Published"), ("HIDDEN", "Hidden")],
                default="PUBLISHED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="producer_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="producer_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="verified_purchase",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="FarmStory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("body", models.TextField()),
                ("educational_content", models.TextField(blank=True, default="")),
                ("seasonal_tag", models.CharField(choices=[("SPRING", "Spring"), ("SUMMER", "Summer"), ("AUTUMN", "Autumn"), ("WINTER", "Winter"), ("ALL_YEAR", "All year")], default="ALL_YEAR", max_length=20)),
                ("image_url", models.URLField(blank=True, default="")),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")], default="DRAFT", max_length=20)),
                ("moderation_status", models.CharField(choices=[("APPROVED", "Approved"), ("HIDDEN", "Hidden")], default="APPROVED", max_length=20)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="farm_stories", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-published_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                ("storage_guidance", models.TextField(blank=True, default="")),
                ("freshness_guidance", models.TextField(blank=True, default="")),
                ("seasonal_tag", models.CharField(choices=[("SPRING", "Spring"), ("SUMMER", "Summer"), ("AUTUMN", "Autumn"), ("WINTER", "Winter"), ("ALL_YEAR", "All year")], default="ALL_YEAR", max_length=20)),
                ("image_url", models.URLField(blank=True, default="")),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")], default="DRAFT", max_length=20)),
                ("moderation_status", models.CharField(choices=[("APPROVED", "Approved"), ("HIDDEN", "Hidden")], default="APPROVED", max_length=20)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipes", to=settings.AUTH_USER_MODEL)),
                ("products", models.ManyToManyField(blank=True, related_name="recipes", to="market_products.product")),
            ],
            options={"ordering": ["-published_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="FavouriteRecipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favourite_recipes", to=settings.AUTH_USER_MODEL)),
                ("recipe", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favourites", to="market_products.recipe")),
            ],
        ),
        migrations.AddConstraint(
            model_name="favouriterecipe",
            constraint=models.UniqueConstraint(fields=("customer", "recipe"), name="unique_favourite_recipe_per_customer"),
        ),
    ]
